---

- name: Prepare Nginx CORS file
  copy:
    src: cors
    dest: "{{ nginx_cors_file }}"
    mode: 0644
- name: Create Nginx configurations file
  template: 
    src: nginx.conf.j2 
    dest: "{{ nginx_conf_file }}"
    mode: 0644 

# 暂时没有auto-restart    
# - name: Create NGINX systemd unit file
#   template:
#     src: nginx.service.j2
#     dest: "{{ nginx_service_file }}"
#     mode: 0744
- name: Restart Nginx service
  systemd: 
    name: nginx
    state: restarted

- name: Setting Nginx logrotate(1/2)
  template:
    src: logrotate.nginx.j2
    dest: "/etc/logrotate.d/nginx"
    mode: 0644
- name: Setting Nginx logrotate(2/2)
  cron:
    name: "rotate nginx log every hour"
    minute: "0"
    hour: "*"
    job: "logrotate -f /etc/logrotate.d/nginx"
    state: present