services:
  cronos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONIKER: myNode01
    ports:
      - "1317:1317"
      - "26657:26657"
    environment:
      - MONIKER=myNode01
    volumes:
      - /root/chain-data/data:/data/.chain-maind/data
      - /root/chain-data/config:/data/configs