services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DOMAIN_NAME=www.domaintest.com
    volumes:
      - /root/nginx/certs:/etc/nginx/certs
      - /root/nginx/logs:/var/log/nginx
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/conf:/etc/nginx/conf.d
